短链接 &&  重置b站短链接与bv链接到av，替换 twitter.com 到 fxtwitter.com
CSUSTers/csust-got pull request #202
Opened 2023-04-24 06:16 UTC by Anthony-Hoo

2023-04-24 06:22 UTC, Rachel030219 approved these changes

2023-04-24 09:28 UTC, icceey requested changes
- 希望域名可以配置喵 [在这里](https://github.com/CSUSTers/csust-got/pull/202/files?diff=unified&w=0#diff-4df197749bb40eefb1da06cc53a262c7e07fd00652acc832cbfce745f39d6227R66)
- 希望可以移除这个id喵 [在这里](https://github.com/CSUSTers/csust-got/pull/202/files?diff=unified&w=0#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034R86-R89)

2023-04-24 09:40 UTC, hugefiver commented on go.mod
> +	github.com/google/go-github/v35 v35.3.0
这是啥

2023-04-24 09:40 UTC, hugefiver commented on go.mod
> +	mvdan.cc/xurls/v2 v2.5.0
这又是啥

2023-04-24 09:51 UTC, hugefiver commented on base/short_url.go
> +func addURLToCSV(client *gh.Client, owner, repo, path, url string) (string, error) {
原子性吗

2023-04-24 09:55 UTC, hugefiver commented on base/short_url.go
> +func generateIdentifier() string {
https://github.com/CSUSTers/csust-got/blob/master/util/randstr.go#L38

2023-04-25 01:26 UTC, Anthony-Hoo commented on base/short_url.go
> +func addURLToCSV(client *gh.Client, owner, repo, path, url string) (string, error) {
原

2023-04-25 01:42 UTC, Anthony-Hoo commented on base/short_url.go
> +func generateIdentifier() string {
> https://github.com/CSUSTers/csust-got/blob/master/util/randstr.go#L38

改了 [这里](https://github.com/CSUSTers/csust-got/pull/202/commits/94085abc5f17c36dc85602cc835c44d08a114d56#diff-4df197749bb40eefb1da06cc53a262c7e07fd00652acc832cbfce745f39d6227R47)

2023-04-25 01:43 UTC, Anthony-Hoo commented on base/short_url.go
> +func addURLToCSV(client *gh.Client, owner, repo, path, url string) (string, error) {
感觉不是很需要关心这个，因为如果别人中途修改了就提交不上去了

2023-04-25 01:43 UTC, Anthony-Hoo commented on go.mod
> +	mvdan.cc/xurls/v2 v2.5.0
那咋办嘛，你写一个url处理库吗

2023-04-25 01:44 UTC, Anthony-Hoo commented
> * 希望域名可以配置喵 [在这里](https://github.com/CSUSTers/csust-got/pull/202/files?diff=unified&w=0#diff-4df197749bb40eefb1da06cc53a262c7e07fd00652acc832cbfce745f39d6227R66)
> * 希望可以移除这个id喵 [在这里](https://github.com/CSUSTers/csust-got/pull/202/files?diff=unified&w=0#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034R86-R89)

都改了

2023-04-25 01:52 UTC, icceey approved these changes
Approved

2023-04-25 03:14 UTC, hugefiver commented on base/short_url.go
> +func addURLToCSV(client *gh.Client, owner, repo, path, url string) (string, error) {
用api的话会直接覆盖的

2023-04-25 03:17 UTC, Anthony-Hoo commented on base/short_url.go
> +func addURLToCSV(client *gh.Client, owner, repo, path, url string) (string, error) {
覆盖了问题也不大，page里面还有就行了

2023-04-25 03:18 UTC, hugefiver approved these changes

2023-04-25 03:40 UTC, Rachel030219 approved these changes

2023-04-25 03:58 UTC, merged